export const ERROR_CODES = {
  // Common
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  // Google OAuth & APIs
  GOOGLE_NOT_CONNECTED: 'GOOGLE_NOT_CONNECTED',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  GOOGLE_TOKEN_REVOKED: 'GOOGLE_TOKEN_REVOKED',
  GOOGLE_SCOPE_MISSING: 'GOOGLE_SCOPE_MISSING',
  GMAIL_API_ERROR: 'GMAIL_API_ERROR',
  SHEETS_API_ERROR: 'SHEETS_API_ERROR',

  // Campaigns & Sending
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',
  CAMPAIGN_NOT_READY: 'CAMPAIGN_NOT_READY',
  CAMPAIGN_ALREADY_RUNNING: 'CAMPAIGN_ALREADY_RUNNING',
  DUPLICATE_LEAD: 'DUPLICATE_LEAD',
  SUPPRESSED_EMAIL: 'SUPPRESSED_EMAIL',
  CIRCUIT_BREAKER_TRIPPED: 'CIRCUIT_BREAKER_TRIPPED',

  // Leads
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  PROVIDER_BUDGET_EXCEEDED: 'PROVIDER_BUDGET_EXCEEDED',

  // AI
  AI_BUDGET_EXCEEDED: 'AI_BUDGET_EXCEEDED',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
